### ISSUE TITLE
Project not marked as affected if dependency upgraded

### ISSUE THREAD

**Issue by paulhobbel** [khalilou88/jnxplus#1020]
There seems to be an issue where rust projects are not affected if a dependency in the versions file gets updated.

We're using dependabot to update our dependencies and if we update a javascript library the projects get marked as affected. This doesn't happen for the gradle projects if we update a gradle dependency.

**Comment by khalilou88** [comment]
Hi @paulhobbel Thanks for raising this issue and this discussion.
Do you speak about the root gradle files?
Do you use `gradleRootDirectory` to isolate nx root project from gradle root project?
Can you fix this with the `Named Inputs` https://nx.dev/recipes/running-tasks/configure-inputs?
Can you produce this with https://github.com/khalilou88/jnxplus-examples repo so we can have a common understanding of the issue?

**Comment by paulhobbel** [comment]
Thanks for the quick response.

> Do you speak about the root gradle files?
If we update a version in `{workspaceRoot}/libs.versions.toml` the gradle projects are not affected

> Do you use gradleRootDirectory to isolate nx root project from gradle root project?
What exactly do you mean by this? This is currently set to `.`

> Can you fix this with the Named Inputs https://nx.dev/recipes/running-tasks/configure-inputs?
I've looked into this as well, that would mean we would have to do something like the following correct?

```
{
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals",
      "!{projectRoot}/**/*.md"
    ],
    "production": ["default"],
    "gradle": [
      "production",
      "{workspaceRoot}/gradle/libs.versions.toml"
    ],
    "sharedGlobals": ["{workspaceRoot}/.github/workflows/pr.yml"]
  },
}
```

I will try to reproduce this with the example project of yours later today

**Comment by khalilou88** [comment]
If you set `gradleRootDirectory`  to `.` or if you don't use it. It's mean you are mixing the nx root project and the gradle root project. So if you change gradle configs you will affect angular or react project for example and I think you don't want that.


I create a PR to explain my idea about using inputs here : https://github.com/khalilou88/jnxplus-examples/pulls

I like your idea but I think is more suitable for a 100% java project.

**Comment by khalilou88** [comment]
I tried to reproduce the issue with https://github.com/khalilou88/jnxplus-examples and everything works fine:
- clone repo
- run `npm i`
- run `nx run-many --target=build`
- run `nx graph --affected`: No project should be marked as affected
- update `{workspaceRoot}/nx-gradle/gradle/libs.versions.toml` by adding a new variable for example
- run `nx graph --affected` again: All projects should be marked as affected

**Comment by paulhobbel** [comment]
It works, adding those files to the inputs fixes the issue we had, thank you very much!
