### ISSUE TITLE
Cannot set property '<project name>' of undefined

### ISSUE THREAD

**Issue by mpscheidt** [khalilou88/jnxplus#11]
Following the instructions at https://dev.to/gridou/how-to-add-spring-boot-and-gradle-multi-project-builds-capabilities-to-your-nx-workspace-53cd and getting this error:

```
D:\workspaces\nximgr\nxinterfacemanager>nx generate @jnxplus/nx-boot-gradle:application interfacemgrboot
√ Which language would you like to use? · java
√ What groupId would you like to use? · imgr
√ What project version would you like to use? · 0.0.1-SNAPSHOT
√ Which packaging would you like to use? · jar
√ Which configuration format would you like to use? · .properties
**Cannot set property 'interfacemgrboot' of undefined**

```

**Comment by paltankov** [comment]
current plugin version is not compatible with workspace version 13.x
in v 13.x the _"projects"_ node was de-supported from _nx.json_ and now resides only in _workspace.json_ and the plugin fails to inject the new module registration snippet.

**Comment by khalilou88** [comment]
@mpscheidt @paltankov Sorry, I will publish a new version for nx 13

**Comment by khalilou88** [comment]
@mpscheidt @paltankov please check the version 1.0.2, it's add the nx 13 support.
