### ISSUE TITLE
release & changelog

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#110]
Hello,

I really appreciate this plugin.
It would be really great if you created releases

**Comment by khalilou88** [comment]
Hi @jbadeau thanks for using this plugin.
Yes I don't use `releases` yet and I should using yet but we have `changlog file` for both plugins  https://github.com/khalilou88/jnxplus/blob/main/packages/nx-boot-gradle/CHANGELOG.md

**Comment by khalilou88** [comment]
Github release is done with jscutlery/semver plugin.
