### ISSUE TITLE
Make maven wrapper optional

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#112]
Hello,

it would be really cool if you could make the dependency on maven wrapper optional as most cicd tools provide maven via containers.

**Comment by khalilou88** [comment]
Hi @jbadeau thanks for using the plugin. Do you have an idea how to make it optional? I think an `Environment Variable` can be good here. I don't want to change every executor.

**Comment by jbadeau** [comment]
yeah, I looked how it’s done in the other nx maven plug-in and it’s on every executor. I think envvar is not so nice so rather just skip it for now

**Comment by jbadeau** [comment]
I have also created a maven plugin which handles releasing:

```json
{
  "name": "spring-boot-public-library",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "library",
  "sourceRoot": "libs/spring-boot-public-library/src",
  "tags": [],
  "targets": {
    "lint": {
      "executor": "@jnxplus/nx-boot-maven:lint",
      "options": {
        "linter": "checkstyle"
      }
    },
    "build": {
      "executor": "@jnxplus/nx-boot-maven:build",
      "outputs": [
        "libs/spring-boot-public-library/target"
      ]
    },
    "test": {
      "executor": "@jnxplus/nx-boot-maven:test",
      "dependsOn": [
        "test"
      ]
    },
    "release": {
      "executor": "@jscutlery/semver:version",
      "dependsOn": [
        "test"
      ],
      "options": {
        "preset": "conventional",
        "tagPrefix": "${projectName}@",
        "push": false,
        "skipCommit": true,
        "commitMessageFormat": "chore(${projectName}): release version ${version} [ci skip]",
        "postTargets": [
          "spring-boot-public-library:,release-gitlab,",
          "spring-boot-public-library:release-mvn"
        ]
      }
    },
    "release-gitlab": {
      "executor": "@jscutlery/semver:gitlab",
      "options": {
        "tag": "${tag}",
        "description": "${notes}"
      }
    },
    "release-mvn": {
      "executor": "@techx/nx-maven:deploy",
      "options": {
        "revision": "${version}"
      }
    }
  }
}
```

Can release an individual versioned module or normal maven shared version

**Comment by khalilou88** [comment]
@jbadeau, yes we can add release and deploy executors.
Could you open PR for that?

**Comment by khalilou88** [comment]
The release executor depends on another plugin.
Making Maven wrapper optional is not recommended but we can add it in a future release if we add an option to not generate it. We can in this case look for the wrapper executables files and in case they don't exist, we skip it and run maven commands.
I will close this issue for now, since no work in planed

**Comment by jbadeau** [comment]
An update.

I have now enablled nx -parallel and I have seen there are concurrency issues with the wapper and its install of maven. Its also an issue in general for mvnw. I have therefore adapted the mvnw and mvnw.cmd scripts to call mvn if on the path otherwise use mvnw
