### ISSUE TITLE
1.2.0 and 1.3.0+ problems

### ISSUE THREAD

**Issue by MrSinisterX** [khalilou88/jnxplus#1132]
Switching from 0.45.0 to 1.1.0 was successful, however, afterwards there are some issues that we encountered:

1. ```1.2.0```: all modules are seen as affected and built even though there are no changes. Before 1.2.0 everything was working as expected. The only change is package.json for switching the plugin version. Both package.json and package-lock.json are nx ignored. Possibly .nxignore is no longer correctly taken into account?
2. ```1.3.0+```: plugin no longer works:

![image](https://github.com/khalilou88/jnxplus/assets/57527771/da35059e-0995-4298-b94a-f81b62f717b8)

**Comment by khalilou88** [comment]
Hi @MrSinisterX 

I think, the problem is du to a breaking change in NX 19.2.0, they remove `projectGraphCacheDirectory` and they change it to `workspaceDataDirectory`.

If you use NX 19.2.0 or higher version, you can use the last version of nx-gradle.

If your version is less that NX 19.2.0. keep 1.2.0 version of nx-gradle.

**Comment by khalilou88** [comment]
In version 1.2.0 we changed the cache folder from `.nx/cache` to `.nx/workspace-data`. Maybe this made the cache not valid.

**Comment by khalilou88** [comment]
same error in nx repo: https://github.com/nrwl/nx/issues/26470

**Comment by MrSinisterX** [comment]
> Hi @MrSinisterX
> 
> I think, the problem is du to a breaking change in NX 19.2.0, they remove `projectGraphCacheDirectory` and they change it to `workspaceDataDirectory`.
> 
> If you use NX 19.2.0 or higher version, you can use the last version of nx-gradle.
> 
> If your version is less that NX 19.2.0. keep 1.2.0 version of nx-gradle.

Thank you for the clarification. Indeed upgrading NX to 19.2.0 or higher works with the latest plugin version.

Also thank you for the awesome work!
