### ISSUE TITLE
parent pom

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#115]
Hello,

Currently I don't see the parent/parent pom connected to the submodules in the nx graph even when I add a root project.json. I suppose the dependency calculation is only calculated via `<dependencies/>` and does not include `</parent>`. I could of course add an implicitDependencies section but this is redundant as the info is in the pom. The effect is that if I change the root pom the submodules are not built as they are not connected in the graph.

Any plans to support parent relationships in the Nx graph?

Cheers

**Comment by jbadeau** [comment]
Will do tomorrow

**Comment by khalilou88** [comment]
Hi @jbadeau, I added the parent project to the dep graph in the version 5.3.0.
Please try it and provide feedback

**Comment by jbadeau** [comment]
Hi. So now I dont see any dependencies in the graph.

I am using:

Nx: 15.9.2
nx-boot-maven: 5.3.0

these are the poms

[poms.zip](https://github.com/khalilou88/jnxplus/files/11186801/poms.zip)

**Comment by khalilou88** [comment]
I believe you have an error in your case. Do you still have a project.json in the root folder ? If yes you need to remove it

**Comment by jbadeau** [comment]
Sorry, was on vacation. Will check tomorrow. If I remove the root project.json then how would I publish/deploy the root Pom to the registry? Thing is, your plugin only handles building but in some of our workflows we release all the artifacts so in those cases I need to be able to release the root Pom as well.

**Comment by khalilou88** [comment]
Hi @jbadeau,  you can not keep `project.json` at the root folder because in this case you can not add `pom.xml` to the root project.
To publish/ deploy the root pom you can use the "run-task" executor and I need to add it in a new version. 

The root project is added like this :
```
  builder.addNode({
    name: parentProjectName,
    type: 'app',
    data: {
      root: '',
      targets: {
        build: {
          executor: '@jnxplus/nx-boot-maven:run-task',
          options: {
            task: '-no-transfer-progress clean install -N',
          },
        },
      },
      files: [
        {
          file: 'pom.xml',
          hash: hasher.hashFile('pom.xml'),
        },
      ],
    },
  });
```
I will add a second line with `run-task` and with this you can publish/deploy the roor project.

**Comment by khalilou88** [comment]
Hi @jbadeau, in the version 5.4.0 when `project.json` exists I used it to create the dep-graph and if not exists I added the project to graph based on the xml file. Maybe you can keep the `project.json` in the root with this version if you want.

**Comment by jbadeau** [comment]
thats great. thanx
