### ISSUE TITLE
[fix] extend with workspace generator

### ISSUE THREAD

**Issue by cladera** [khalilou88/jnxplus#118]
As a developer I want to create a workspace generator that extends jnxplus' application generator, for example, to add new dependencies to the generated pom file.

The existing generators barrel exports all the generators but the generators' entry point functions are declared without a name, which makes it impossible to import and therefore to be called from another generator.

Here is a simplified code I'm trying to create:

```
import { Tree } from '@nrwl/devkit';
import { ApplicationGeneratorSchema } from './schema';
import { applicationGenerator } from '@jnxplus/nx-boot-maven/generators';

async function extendedApplicationGenerator(
  tree: Tree,
  options: ApplicationGeneratorSchema
) {
  // Create a jnxplus application
  await applicaitonGeneartor(options);

  // Add additional dependencies to the pom file
  await addDependencies();
}
export default extendedApplicationGenerator;
```

**Comment by khalilou88** [comment]
@cladera Thanks, it's published in the new version 5.1.1
