### ISSUE TITLE
jnxplus/nx-boot-maven init fails

### ISSUE THREAD

**Issue by cladera** [khalilou88/jnxplus#121]
`nx-boot-maven:init` generator fails when running on an empty repo.

Reproduce steps
1. Create a new workspace `npx create-nx-workspace@latest name`
2. Install nx-boot-maven plugin `npm install --save-dev @jnxplus/nx-boot-maven`
3. Try to initialise the parent module `npx nx g @jnxplus/nx-boot-maven:init`

Result
```
> NX Cannot find .prettierrc
```

Nx Version: v15.9.2
jnxplus/nx-boot-maven Version: 5.1.1

**Comment by jbadeau** [comment]
I have seen that this plugin expects .prettierrc
.prettierignore to present in the workspace when calling init.
I would change the code to check first if the file exists before modifying them. Prettier will most likey not be present in a non js/ts workspace

**Comment by khalilou88** [comment]
@cladera, @jbadeau Now I fixed this issue in the 5.2.2 version.

**Comment by jbadeau** [comment]
Thanx fir the great support by the way
