### ISSUE TITLE
Could not format pom.xml ...

### ISSUE THREAD

**Issue by networkinss** [khalilou88/jnxplus#1215]
I get error messages adding an application or library.  
I have a sample repo here:  
[(https://github.com/networkinss/nxsamplemaven)]
It has a full example of the output in the READM.md.  
Here an extract:
> 
> Could not format pom.xml. Error: "require() of ES Module /home/amrit/WebstormProjects/nx/maven/nxmavensample/node_modules/.pnpm/@prettier+plugin-xml@3.4.1_prettier@2.8.8/node_modules/@prettier/plugin-xml/src/plugin.js from /home/amrit/WebstormProjects/nx/maven/nxmavensample/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js not supported.
> Instead change the require of plugin.js in /home/amrit/WebstormProjects/nx/maven/nxmavensample/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js to a dynamic import() which is available in all CommonJS modules."
> Could not format apps/springservice/project.json. Error:
> 

Let me know if maybe that is a version problem.
Here the nx report output:  

# nx report
Node           : 18.18.2
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 8.10.5

nx (global)        : 19.3.0
nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
@jnxplus/nx-maven
---------------------------------------
Community plugins:
@jnxplus/nx-maven : 1.7.3

**Comment by khalilou88** [comment]
Hi @networkinss , I see in your repo that you have old version of  prettier `"prettier": "^2.6.2"`. jnxplus only support version 3.

**Comment by khalilou88** [comment]
I think `init generator` should show a warning or force the version 3.

**Comment by networkinss** [comment]
Sure, nx creates a workspace with prettier v2.6.2.
After changing it to version 3.0.0 it does run into those error messages.
But that means it is running into this error by default with current version of NX, right ?

**Comment by khalilou88** [comment]
@networkinss I used the last version of prettier and everything is working fine. check this fork of your repo
https://github.com/khalilou88/nxsamplemaven
I added two commits.

**Comment by khalilou88** [comment]
I also removed `pnpm-lock.yaml` but i don't think this is the problem.

**Comment by khalilou88** [comment]
fix for the issue https://github.com/khalilou88/jnxplus/pull/1216

**Comment by networkinss** [comment]
Thanks for the help.
