### ISSUE TITLE
Cannot read properties of undefined (reading 'projects')

### ISSUE THREAD

**Issue by ToppScorer** [khalilou88/jnxplus#1249]
Since upgrading from version `0.22.7` to version `0.24.5-next.0` or higher, after running `nx reset` and and then trying to run an arbitrary nx task, I'm always getting 

```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "@jnxplus/nx-maven" plugin threw an error while creating dependencies:
    TypeError: Cannot read properties of undefined (reading 'projects')
        at Object.createDependencies (/Redacted/.nx/installation/node_modules/@jnxplus/nx-maven/src/graph/create-dependencies.js:10:36)
        at LoadedNxPlugin.createDependencies (/Redacted/.nx/installation/node_modules/nx/src/project-graph/plugins/internal-api.js:60:59)
```

What do I have to do to prevent that? Seems to have something to do, with no cache data being available.

**Comment by khalilou88** [comment]
Hi @ToppScorer      
How about 0.45.0 version, the last version before to go to 1.0.0 version?
which version of Nx do you use ?

**Comment by khalilou88** [comment]
I also recommend you trying version 1.1.0.
If you use Nn 19.2.0+ version, use the latest version of the plugin.

**Comment by ToppScorer** [comment]
I tried to use the newest version of Nx (19.6.2) and the plugin (1.8.0) first, which gave the same error message. Then went up each version from my old setup, to find out when it would still work. 0.24.5-next.0 was the version which didn‘t work.

**Comment by khalilou88** [comment]
@ToppScorer, Since this version, we changed graph calculation.
I think the issue it's only about `Integrated Repository`. Because smoke tests ate working fine for `Package-Based Repos`.
Could you please share a reproduction?

**Comment by ToppScorer** [comment]
@khalilou88 I will try to do that, but it will take some time. 

Maybe in the meantime you can see from the stack trace, that the first call from Nx is made to the `createDependencies` method, which then immediately calls `getCachedWorkspaceData` (https://github.com/khalilou88/jnxplus/blob/1cd1e5bf80bca24ed39709a1ed82ea3d925a2097/packages/nx-maven/src/graph/create-dependencies.ts#L26C14-L26C75), which is returning `undefined`. Seems that a call to `getWorkspaceData` is missing in this case to initialize the cache?

**Comment by khalilou88** [comment]
Cant reproduce the issue:

1. I cloned this repo : `https://github.com/spring-guides/gs-spring-boot`
2. In complete folder i run : `npx nx@latest init` 
3. I added nx-maven to nx.json :
```
{
  "installation": {
    "version": "19.6.2",
    "plugins": {
      "@jnxplus/nx-maven": "1.8.0"
    }
  },
  "plugins": [
    "@jnxplus/nx-maven"
  ]
}
```
4. Run :  `nx graph`

I also tried `mavenRootDirectory` option.

@ToppScorer maybe you are using an option to disable writing in cache folder ?

**Comment by khalilou88** [comment]
Cached data is calculated during `CreateNodes` function.
```
export const createNodes: CreateNodes<NxMavenPluginOptions> = [
  'nx.json',
  (_, opts) => {
    const workspaceData: WorkspaceDataType = getWorkspaceData(opts);
```

**Comment by ToppScorer** [comment]
@khalilou88 I created a branch in my test-repo as an example https://github.com/ToppScorer/test-monorepo/tree/jnxplus

When running `nx backend-build example-lib-parent --verbose` you can see the error. When changing the version to `0.24.4` it works.

**Comment by khalilou88** [comment]
@ToppScorer Remove `nx.json` from `.nxignore`.
`CreateNodes` is not called in your case because `nx.json` is ignored.

I already opened an issue for that in nx repo to call `CreateNodes` without file : https://github.com/nrwl/nx/discussions/23340

**Comment by ToppScorer** [comment]
@khalilou88 Ok, then it's working. For my purposes not ideal, but this ticket can be closed then. Thanks ✌️
