### ISSUE TITLE
Parallel builds don't wait for dependent modules to be build

### ISSUE THREAD

**Issue by edwinvanderelst** [khalilou88/jnxplus#1262]
I have a multi-module project, with some 'pom' modules, like this:
```
applications/app/pom.xml (dependency on common/service)
common/pom.xml (pom.xml with 2 modules, service & model)
common/service/pom.xml (dependency on common/model)
common/model/pom.xml
```

When I build all: `nx run-many -t build`
It fails on service not finding model in the repository, because it runs the build for model & service in parallel (I think)

If I first run a build of model (nx run model:build), service does build.

I don't think it has to do with concurrent access to the .m2/repository, but with the order of the builds. I see service & model running in parallel.
Also, when I execute `nx run-many -t build` twice, I do get a successful build (because 'model' was build in the first run, where service failed on not finding model)

**Comment by edwinvanderelst** [comment]
when I build with --parallel=false the build succeeds

**Comment by khalilou88** [comment]
3. Witch OS do you use ? windows can have this issue more than Linux
4. Do you use maven wrapper ? not using wrapper can give better results.
Example in GitHub actions:
```
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
```

**Comment by edwinvanderelst** [comment]
I upgrade maven to 3.9.9, on OSX
I'm not using the maven wrapper.

I will try to create a smaller reproduction (my build is rather big, with multiple nested pom's)

**Comment by edwinvanderelst** [comment]
you are a hero :-)

I was missing the "dependsOn": ["^build"]
