### ISSUE TITLE
outputDirLocalRepo stopps working with newest nx version (19.8.3)

### ISSUE THREAD

**Issue by shanon84** [khalilou88/jnxplus#1319]
Hallo,
after upgrading my dependencies my targets using {option.outputDirLocalRepo} as an output are failing:
`D:\gits\monorepo\node_modules\nx\src\hasher\native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: "{options.outputDirLocalRepo}" is an invalid fileset.
All filesets have to start with either {workspaceRoot} or {projectRoot}.
For instance: "!{projectRoot}/**/*.spec.ts" or "{workspaceRoot}/package.json".
If "{options.outputDirLocalRepo}" is a named input, make sure it is defined in nx.json.`

A quickfix seems to be to add
`"{options.outputDirLocalRepo}": []`
into the namedImports

**Comment by khalilou88** [comment]
Hi @shanon84, I don't think so. The smoke tests using this versions are working fine.
You have an issue in your config, I think you are using an absolute path for `options.outputDirLocalRepo`. `options.outputDirLocalRepo` should be a relative path to {workspaceRoot}.

Do you use `localRepoRelativePath`?

**Comment by shanon84** [comment]
well, it worked until I upgraded jnxplus and nx to the newest version.
yes, I am using localRepoRelativePath:
`"localRepoRelativePath": ".m2/repository"`
I asume the outputDirLocalRepo is set by the plugin with localRepoRelativePath + "project groupId+artifactid from pom" automatically?

**Comment by khalilou88** [comment]
Yes you can run `nx show project project-name` to see it's value.

**Comment by khalilou88** [comment]
I tried to put invalid output but I didn't get same error like you:

- Target with invalid output:
```
    "build": {
      "executor": "@jnxplus/nx-maven:run-task",
      "outputs": [
        "{projectRoot}/target",
        "C:\\Users\\khali\\.m2\\repository\\com\\example\\m-sb-lib\\0.0.0-SNAPSHOT",
        "{projectRoot}/.flattened-pom.xml"
      ],
      "options": {
        "task": "install -DskipTests=true"
      }
    },
```
- Error:
```
PS D:\Workspace\Projects\jnxplus-examples> nx build m-sb-lib --skip-nx-cache --verbose

 NX   The following outputs are invalid: 

 - C:\Users\khali\.m2\repository\com\example\m-sb-lib\0.0.0-SNAPSHOT

Run `nx repair` to fix this.
Error: The following outputs are invalid: 
 - C:\Users\khali\.m2\repository\com\example\m-sb-lib\0.0.0-SNAPSHOT
```

**Comment by khalilou88** [comment]
I need the `nx.json` and a `project.json` examples to reproduce this issue.

**Comment by shanon84** [comment]
here is my repo:
https://github.com/shanon84/monorepo

**Comment by khalilou88** [comment]
@shanon84 I couldn't reproduce it.
Can you clone your project in a new folder, remove `"{options.outputDirLocalRepo}": []` and run a fresh `npm i` or yarn?
Maybe you need just a new node_modules?

**Comment by khalilou88** [comment]
Similar issue here in NX repo: https://github.com/nrwl/nx/issues/27899

**Comment by shanon84** [comment]
Also auch nach einem Löschen des node_modules (und caches) konnte ich das Problem wieder sehen.
Hattest du ein yarn unittest-BE ausgeführt? Denn das Problem ist ja das outputDirLocalRepo als Input.

**Comment by khalilou88** [comment]
@shanon84 I didn't use `unittest-BE`, I used `build-BE`.

- `unittest-BE` don't work because you use `{options.outputDirLocalRepo}` as input:

```
PS D:\Workspace\Projects\monorepo-77> nx unittest-BE my-lib1 --skip-nx-cache --verbose

 NX   Daemon process terminated and closed the connection

Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in: D:\Workspace\Projects\monorepo-77\.nx\workspace-data\d\daemon.log
```
Removing `{options.outputDirLocalRepo}` from inputs make the target works

**Comment by khalilou88** [comment]
Finally, I produce it. I need to disable NX daemon : `$env:NX_DAEMON='false'`
```
PS D:\Workspace\Projects\monorepo-77> nx unittest-BE my-lib1 --skip-nx-cache --verbose

 NX   "{options.outputDirLocalRepo}" is an invalid fileset.

All filesets have to start with either {workspaceRoot} or {projectRoot}.
For instance: "!{projectRoot}/**/*.spec.ts" or "{workspaceRoot}/package.json".
If "{options.outputDirLocalRepo}" is a named input, make sure it is defined in nx.json.

Error: "{options.outputDirLocalRepo}" is an invalid fileset.
All filesets have to start with either {workspaceRoot} or {projectRoot}.
For instance: "!{projectRoot}/**/*.spec.ts" or "{workspaceRoot}/package.json".
If "{options.outputDirLocalRepo}" is a named input, make sure it is defined in nx.json.

    at NativeTaskHasherImpl.hashTasks (D:\Workspace\Projects\monorepo-77\node_modules\nx\src\hasher\native-task-hasher-impl.js:32:36)
```

**Comment by khalilou88** [comment]
If you add `{options.outputDirLocalRepo}` to outputs it will work because in this case we will calculate the value of `outputDirLocalRepo` and add it to options object.

We need to look in inputs to make it work in your case, but I don't think it's a valid use case ?

**Comment by khalilou88** [comment]
PR here https://github.com/khalilou88/jnxplus/pull/1321, but need to think about it more

**Comment by shanon84** [comment]
Well, my idea behind it was to have it in the cache calculation. I think having the existing project files (pom.xml+src folder) and the previous ones should be enough.

`        "build-files",
        "^build-files",
        "{projectRoot}/target",
        "{options.outputDirLocalRepo}"`
I think I could only use the first two and remove the other two. But I am not certain about the hash calculation. If it is enough to have a correct calculation. Especially with a remotecache in action.

**Comment by khalilou88** [comment]
I am more about throwing an error if `options.outputDirLocalRepo` is used in inputs: https://github.com/khalilou88/jnxplus/pull/1322

**Comment by khalilou88** [comment]
I like this idea in your repo 
```
  "namedInputs": {
    "maven": [
      "{projectRoot}/src/**/*",
      "{projectRoot}/pom.xml",
      "{projectRoot}/project.json"
    ],
```

I suggest naming it `defautMaven` and add `productionMaven` for `productionMaven` you can exclude test files

```
  "namedInputs": {
    "defaultMaven": [
      "{projectRoot}/src/**/*",
      "{projectRoot}/pom.xml",
      "{projectRoot}/project.json"
    ],
    "productionMaven": [
      "defaultMaven",
      "!{projectRoot}/src/test/**/*"
    ],
```
