### ISSUE TITLE
Support for plugin dependencies

### ISSUE THREAD

**Issue by PieterVanEde** [khalilou88/jnxplus#1342]
In a parent I have a plugin (arch-unit) which has a plugin dependency on a rule set that itself is a module in the pom (so listed in the modules section).

Maven itself recognizes that after the parent, it should first build the module that is used as a plugin-dependency, so that it is available for other modules.

Nx-maven however does not see this dependency. It does not create dependencies in the graph and therefore it sometimes builds/tests a project that has a dependency on another for execution it's plugin, but that project has not been built yet.

Is this a known issue?

**Comment by khalilou88** [comment]
@PieterVanEde 

I know this case based on jnxplus-examples: https://github.com/khalilou88/jnxplus-examples/blob/main/nx-maven/pom.xml
It's not covered by `nx-maven` because it will create a circular dependency if the parent project is also the aggregator project.
You can use `implicitDependencies` to link this project to your parent project.

I will add this feature and in this case we need to separate aggregator project from parent project. Maybe I will add a flag to not break other projects: `SkipPluginDependencies`!

**Comment by PieterVanEde** [comment]
Would be great indeed to support this. It is indeed possible to create circular dependencies, but that would only happen if a vanilla mvn build would also fail I guess.

**Comment by PieterVanEde** [comment]
Would it also be possible to backport this to the 0.x version range? I'm unfortunately in a project still stuck at NX 18 at the moment, but I would really be happy to use this functionality. Given the number of projects, it would be a chore (and fragile) to depend on developers manually adding the correct `implicitDependencies`

**Comment by khalilou88** [comment]
@PieterVanEde OK

**Comment by PieterVanEde** [comment]
That's great! Out of curiosity, what is the expected timeline when you expect this functionality to arrive in nx-maven?

**Comment by PieterVanEde** [comment]
That's great! Will it also look in the plugin(management) section of the parent?

**Comment by khalilou88** [comment]
For `pluginManagement`  I need an example. I am using `jnxplus-examples` for cases

**Comment by PieterVanEde** [comment]
No problem, very valid request. I've raised a PR for an example where a `dependency` is specified in the `pluginManagement` section: https://github.com/khalilou88/jnxplus-examples/pull/308

**Comment by khalilou88** [comment]
@PieterVanEde 
You can test the version 1.13.0-next.0

**Comment by khalilou88** [comment]
@PieterVanEde 
I published also version 0.50.0-next.0 for NX 18.3.5

**Comment by PieterVanEde** [comment]
I will perform a test right away!

**Comment by PieterVanEde** [comment]
This now works almost correctly.

What works correctly:
- a dependency is created from the parent pom to the project holding the plugin dependency
- this is created as a circular dependency like you predicted

What I find strange:
- Maven itself does not create a circular dependency, because I have implemented a (hack, I admit) from https://stackoverflow.com/questions/12924634/define-maven-plugins-in-parent-pom-but-only-invoke-plugins-in-child-projects. This hack allows me to specify the desired configuration and execution in the `pluginManagement` section of my root pom.xml, but in the `plugins` section to erase the phase. Net result: in the parent pom the plugin is not executed, and in all children the plugin is executed.

Code is perhaps clearer:

```xml
<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <!-- Main declaration and configuration of the plugin -->
                <!-- Will be inherited by children -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.9.1</version>
                <executions>
                    <execution>
                        <!--This must be named-->
                        <id>checkstyle</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <!-- You may also use per-execution configuration block -->
                <configuration...>
            </plugin>
        </plugins>
    </pluginManagement>
    <plugins>
        <plugin>
            <!-- This declaration makes sure children get plugin in their lifecycle -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-checkstyle-plugin</artifactId>
            <!-- Configuration won't be propagated to children -->
            <inherited>false</inherited>
            <executions>
                <execution>
                    <!--This matches and thus overrides execution defined above -->
                    <id>checkstyle</id>
                    <!-- Unbind from lifecycle for this POM -->
                    <phase>none</phase>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

This would mean that you have to reason over the effective pom and disregard a plugin if it is not bound to a phase. I don't know how feasible that is.

Alternatively I could seperate my module specification and my plugin/dependency specification in two layered parent poms, but I would rather not do that.

**Comment by khalilou88** [comment]
I added more code to https://github.com/khalilou88/nx-maven-examples.
Run `nx graph` to understand the architecture

**Comment by khalilou88** [comment]
@PieterVanEde I published version 0.50.0 for NX 18.3.5 and 1.13.0 for NX 20.

**Comment by PieterVanEde** [comment]
Great, thanks a lot!

**Comment by PieterVanEde** [comment]
Sorry to get back to this, I just had some sime to also review the code. I see the current implementation (if I don't misread the code) _only_ looks at plugin dependencies specified in pluginDependencies. However, I think this is a little too narrow approach. I'll try to file a PR that also looks at regular plugin dependencies.

**Comment by PieterVanEde** [comment]
And there I did misread the code, your implementation really is sound.
