### ISSUE TITLE
Checkstyle versions

### ISSUE THREAD

**Issue by yusijs** [khalilou88/jnxplus#141]
We got a weird error from checkstyle which led me to investigate a bit, and I noticed that checkstyle is actually retrieved from one of your packages and it's a fairly old version:

```
❯ java -jar ./node_modules/@jnxplus/checkstyle/checkstyle.jar --version
Checkstyle version: 9.3
```

This is mostly fine (I think our issue is not necessarily related), but this should be a bit more transparent. 

A few ways I can think of to improve this:
* Allow passing in a checkstyle version to use in options, which is then downloaded as required from [maven](https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/)
* * ```        "lint": {
            "executor": "@jnxplus/nx-boot-maven:lint",
            "options": {
                "linter": "checkstyle",
                "version": "10.9.3"
            }
        }
* Keep it as is, but make it clearer that it uses a bundled checkstyle.jar file. Personally I'm a bit concerned with this from a security perspective
* Allow passing in a path to which checkstyle.jar file to use, so we can use a package we have downloaded and verified ourselves.
* * ```        "lint": {
            "executor": "@jnxplus/nx-boot-maven:lint",
            "options": {
                "linter": "checkstyle",
                "jar": "tools/jar/checkstyle.jar" // example path, relative to project root
            }
        }

**Comment by khalilou88** [comment]
Hi @yusijs Thanks for this issue. I have the idea to remove this project for the security reasons you mentioned and also because it's hard to maintain this way. 
I will make the change to use the maven plugin

**Comment by khalilou88** [comment]
Hi @yusijs, The maven plugin didn't work for me because there is no way to add a global checkstyle xml file without adding a new sub project. From the new version 5.4.0, checkstyle  jar is downalded from checkstyle  github repo. To specify a version you can add a property in the root xml file like this 

```
  <properties>
    <checkstyle.version>10.9.3</checkstyle.version>
  </properties>
```

**Comment by yusijs** [comment]
We're seeing the same issue still - I guess it's because we kick off multiple lint-jobs in parallel at the same time, and they start downloading checkstyle.jar more or less at the same time. Perhaps this should be ran during install as well, which would allow us to update the checkstyle-version by changing it in the pom.xml (and running lint)?

**Comment by khalilou88** [comment]
@yusijs I was thinking about the same idea but I didn't go far in analysis, maybe a post install script at the plugin level can save this issue 
` "postinstall": "node installLinters.js"`

**Comment by khalilou88** [comment]
@yusijs please try version 5.4.2

**Comment by yusijs** [comment]
@khalilou88 that seems to have solved it, thanks!
