### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by nosaku** [khalilou88/jnxplus#174]
Trying to do "nx migrate next" and then npm install

Got this error

npm ERR! Found: @nrwl/workspace@16.1.0-rc.1
npm ERR! node_modules/@nrwl/workspace
npm ERR!   dev @nrwl/workspace@"16.1.0-rc.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nrwl/workspace@">=14.0.0" from @jnxplus/nx-boot-maven@5.4.2
npm ERR! node_modules/@jnxplus/nx-boot-maven
npm ERR!   dev @jnxplus/nx-boot-maven@"^5.4.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by nosaku** [comment]
"peerDependencies": {
    "@nrwl/devkit": ">=14.0.0",
    "@nrwl/workspace": ">=14.0.0",
    "@nrwl/tao": ">=14.0.0"
  }

I think these are now scoped as "@nx"?

**Comment by khalilou88** [comment]
Hi @nosaku, The main branch is up to date with version NX 16.0.3. I will update to version NX 16.1.0 and published versions for the plugins

**Comment by khalilou88** [comment]
@nosaku Please use the version 6.0.1 for NX 16 version support

**Comment by nosaku** [comment]
Thank you so much.

Sent from Yahoo Mail on Android 
 
  On Sat, May 6, 2023 at 7:55 PM, ***@***.***> wrote:   


Closed #174 as completed.
