### ISSUE TITLE
Support Non root parent pom

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#354]
Currently the parent pom is expected to be at the root of the workspace but this is not always desirable for the following:

- Forces the root project of a polyglot repo to be maven based (the project name should be workspace or similar and not the artifactId of the parent pom)
- Many projects put the parent pom in its own folder

**Comment by khalilou88** [comment]
@jbadeau for the second point it's possible with maven plugin. You can generate a parent-project and make it your parent POM. But we need a root pom as a aggregator for all projects.

- Root Pom:  aggregator for all projects and for versions
- Parent project, put it where you want, you can have a parent project for libs and other for apps. And make apps parent project extend libs parent project...

You can check nx-maven e2e test for this, but yes it's need documentation 


For the first point, i don't know if it's possible

**Comment by jbadeau** [comment]
Hello there,

I have tried your suggestion and it works but I noticed an issue in the affected graph. If I have a pom.xml at the repo root and I modify any other file (e.g. README.MD) in the root I get an affected graph of all the maven projects. In this case I have no project.json at the root.

I am using:

- nx: 16.7.2
- @jnxplus/nx-boot-maven: 7.3.0

**Comment by khalilou88** [comment]
this feature is tracked in this new issue: https://github.com/khalilou88/jnxplus/issues/519
during init we will give the user an option to choose a subfolder for all maven projects (another feature will be for gradle projects).
closing the issue
