### ISSUE TITLE
Upcoming Official Java support for Nx

### ISSUE THREAD

**Issue by FrozenPandaz** [khalilou88/jnxplus#358]
Hi Khalil,

I am one of the leads on the Nx team.

Firstly, I would like to thank you for maintaining the jnxplus plugins for Java. It is awesome to see the community take the initiative on adding support for other languages to Nx. It takes a lot of time and effort.

The Nx team has been utilizing Java, Kotlin, and Gradle more and more for different things such as:
* Our React Native plugin
* Our Nx Console IntelliJ plugin
* Our Nx Cloud API

As such, we want to introduce a first party Nx plugins for Gradle, Kotlin, Java and maybe more technologies in the Java ecosystem down the line. We know that this will possibly overlap with your plans. We would be happy for you to contribute to the first party plugin as we start developing it. Our initial plans are to focus on supporting Gradle but will probably expand in the future.

I think there are plenty of areas where the first party Nx Plugins and jnxplus are not likely to overlap anytime soon such as Flutter, Melos, Micronaut, Quarkus, etc. If there does end up becoming overlap in support, I think having alternatives is a good thing so you could continue to develop those areas. Or you could choose to stop supporting those areas in favor of the first party plugin so that you can focus on other areas.

Do you have any questions or concerns?

Thank you!

**Comment by khalilou88** [comment]
Hi @FrozenPandaz Thanks for kind words, that is a big new that nx will add support for gradle and it's not a problem for me. I will continue maintaining this repo and adapt it to use code from the official nx support.
Curious about the nx integration and ready to help if deeded :)

**Comment by jbadeau** [comment]
That’s good news although I’m sad that maven isn’t first 🥺 but it’s good news. We have been using Java and nx for sometime.

**Comment by khalilou88** [comment]
@jbadeau It's seems logical for me because unfortunately I notice two problems  with nx + maven integration:
- The cache issue that you already mentioned
- Run many build in parallel fails randomly, maybe it will be fixed in future release of maven

This issues don't exits with Gradle

**Comment by jbadeau** [comment]
Parallel has issues due to nx not correctly building dependencies before projects. I have opened an issue about this but the unfortunately have not received any feedback.

**Comment by khalilou88** [comment]
@jbadeau I created the issue https://github.com/khalilou88/jnxplus/issues/700 to discuss a solution for Parallel-Build.

**Comment by khalilou88** [comment]
@nx/gradle is published : https://nx.dev/blog/2024-05-08-nx-19-release
