### ISSUE TITLE
Manage arguments in nx serve with maven plugin

### ISSUE THREAD

**Issue by matteolapini** [khalilou88/jnxplus#39]
When I execute the command
`nx serve application-name`

I would like to add some arguments, for example: 
`nx serve application-name --args="-Dspring-boot.run.profiles=dev"`

This arguments must be concatenated to the command `spring-boot:run`. For example:
`./mvnw spring-boot:run -pl :application-name  -Dspring-boot.run.profiles=dev`

## Example of implementation

In file:
`packages/nx-boot-maven/src/executors/serve/executor.ts`
change
```
  const result = runCommand(
    `${getExecutable()} spring-boot:run -pl :${context.projectName}`
  );
```
in
```  var args = options?.['args'] ?? '';
  const result = runCommand(
    `${getExecutable()} spring-boot:run -pl :${context.projectName} ${args}`
  );```

**Comment by khalilou88** [comment]
Hello @matteolapini, 
Thank you for this issue, what you ask is a valid use case. 
I added args in the version 2.1.0 for maven plugin.
Please use it et give me a feedback.

**Comment by ToppScorer** [comment]
@khalilou88 Could this also be added to the nx-maven run-task executor?

**Comment by khalilou88** [comment]
@ToppScorer yes and it's more easy with run-task executor, you can choose the command to be executed in `project.json` and updated as you need.
if one line is not enough you can use task as array.

I need to work more on docs

**Comment by khalilou88** [comment]
@ToppScorer if you want to add a global arg, you can use this env variable: 
```
        env:
          NX_MAVEN_CLI_OPTS: '--no-transfer-progress -Dmaven.plugin.validation=VERBOSE'
```

**Comment by khalilou88** [comment]
@ToppScorer I don't think it's a good idea, for me it's over-engineering. In the past i had an option also called `skipClean`  and i need to add more options for more use cases...

But I think to add this option:
- cwd : Current working directory of the commands. If it's not specified the commands will run in the maven working directory.
If cwd  is used, the `-pl :project` part will not be generated.

**Comment by khalilou88** [comment]
another reason to not add `args`  option is to have just one place to understand the command that will be executed.

**Comment by khalilou88** [comment]
Actually there is a use case of `args` option is when you want to add `args` just with command line and you don't want to add this `args` to the `project.json` with `task` option. I think the best solution here is to override the `task` option:

`nx serve --task="my_command my-args"`
