### ISSUE TITLE
Use Azure Maven@3 task

### ISSUE THREAD

**Issue by nosaku** [khalilou88/jnxplus#489]
Currently i am using the mvn wrapper. But the problem is that in Azure I use a different corporate proxy and in local a different one. So adding these in .mvn/jvm.config is problematic. Is there a way I can use the Azure Maven@3 task to make mvn available for the nx?

**Comment by khalilou88** [comment]
This feature was already asked, I will make the wrapper optional during init. And generate the correct command. But you will need to migrate to nx-maven because others plugins are not maintened

**Comment by khalilou88** [comment]
@nosaku I published a new version with optional wrapper. Remove `.mvn folder` with executables to use the `mvn` command.

In local machine, if you don't have maven installed, you can use wrapper generator to add a wrapper. The generator will add the wrapper to `.gitignore` so nx will ignore it

**Comment by khalilou88** [comment]
I choose this solution to not generate extra files that we don't need. But if you want to keep the wrapper, i can add a system variable that you set on azure: NX_SKIP_MAVEN_WRAPPER

**Comment by nosaku** [comment]
Thank you, @khalilou88. How do I use mvn command in Azure pipeline? Usually maven task in Azure needs a goal to run. But in this case it is controlled by nx.

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 5, 2023 at 2:49 AM, ***@***.***> wrote:   


I choose this solution to not generate extra files that we don't need. But if you want to keep the wrapper, i can add a system variable that you set on azure: NX_SKIP_MAVEN_WRAPPER

**Comment by khalilou88** [comment]
This feature allow just to use the same maven from azure. So you don't have to duplicate config in wrapper folder. 
I don't think you can use maven task here with goals, if you can debug the command try to copy it in the project.json

**Comment by nosaku** [comment]
Yeah got it will give a try. Thank you.

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 5, 2023 at 3:01 AM, ***@***.***> wrote:   


This feature allow just to use the same maven from azure. So you don't have to duplicate config in wrapper folder.
I don't think you can use maven task here with goals, if you can debug the command try to copy it in the project.json

**Comment by nosaku** [comment]
when I run the build, it is not terminating even after success

**Comment by nosaku** [comment]
When I ran on my local Windows laptop, it just stuck forever and when I press enter key it show "build successful" but didn't terminate. I ran npm script from package.json which calls the nx build. And when running in Azure pipeline using Ubuntu self hosted agent... it takes long time.. like I am waiting for last 5 mins and never terminates.
