### ISSUE TITLE
nx-boot-maven postinstall error: invalid or corrupt jarfile

### ISSUE THREAD

**Issue by gitLinda** [khalilou88/jnxplus#502]
Hi,

I'm using nx-boot-maven version 7.3.0 and getting sometimes an error when installing the dependencies.
The error is not consistent. Could it be that repository mirrors cause the issue? The jar file might be corrupted in one location. That would explain why it sometimes works and sometimes not.

I know that I should switch to nx-maven instead of nx-boot-maven, but I need to wait until some of the current open issues there are fixed.

Error log:
`
$ pnpm install --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1674
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1674, reused 0, downloaded 0, added 0
Progress: resolved 1674, reused 0, downloaded 134, added 126
Progress: resolved 1674, reused 0, downloaded 354, added 359
Progress: resolved 1674, reused 0, downloaded 531, added 583
Progress: resolved 1674, reused 0, downloaded 814, added 898
Progress: resolved 1674, reused 0, downloaded 1067, added 1153
Progress: resolved 1674, reused 0, downloaded 1335, added 1421
Progress: resolved 1674, reused 0, downloaded 1555, added 1645
Progress: resolved 1674, reused 0, downloaded 1581, added 1674, done
.../node_modules/@jnxplus/nx-boot-maven postinstall$ node src/scripts/install-linters.js
.../node_modules/@jnxplus/nx-boot-maven postinstall$ node src/scripts/install-linters.js
.../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../es5-ext@0.10.62/node_modules/es5-ext postinstall$  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
.../node_modules/@parcel/watcher install$ node-gyp-build
.../node_modules/core-js-pure postinstall: Done
.../es5-ext@0.10.62/node_modules/es5-ext postinstall: Done
.../node_modules/@parcel/watcher install: Done
.../node_modules/styled-components postinstall$ node ./postinstall.js
.../node_modules/styled-components postinstall: Done
.../node_modules/@jnxplus/nx-boot-maven postinstall: Error: Invalid or corrupt jarfile /builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/@jnxplus/tools/linters/ktlint/ktlint
.../node_modules/@jnxplus/nx-boot-maven postinstall: node:internal/errors:867
.../node_modules/@jnxplus/nx-boot-maven postinstall:   const err = new Error(message);
.../node_modules/@jnxplus/nx-boot-maven postinstall:               ^
.../node_modules/@jnxplus/nx-boot-maven postinstall: Error: Command failed: java -jar /builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/@jnxplus/tools/linters/ktlint/ktlint --version
.../node_modules/@jnxplus/nx-boot-maven postinstall: Error: Invalid or corrupt jarfile /builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/@jnxplus/tools/linters/ktlint/ktlint
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at checkExecSyncError (node:child_process:885:11)
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at execSync (node:child_process:957:15)
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at isAnotherVersion (/builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/.pnpm/@jnxplus+common@0.10.0_@nx+devkit@16.9.1/node_modules/@jnxplus/common/src/lib/utils/index.js:94:53)
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at /builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/.pnpm/@jnxplus+common@0.10.0_@nx+devkit@16.9.1/node_modules/@jnxplus/common/src/lib/utils/index.js:85:18
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at Generator.next (<anonymous>)
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at /builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at new Promise (<anonymous>)
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at Object.__awaiter (/builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:163:16)
.../node_modules/@jnxplus/nx-boot-maven postinstall:     at getKtlintPath (/builds/juliusbaer/techx/sandboxes/linda/test-dir-option/node_modules/.pnpm/@jnxplus+common@0.10.0_@nx+devkit@16.9.1/node_modules/@jnxplus/common/src/lib/utils/index.js:67:20) {
.../node_modules/@jnxplus/nx-boot-maven postinstall:   status: 1,
.../node_modules/@jnxplus/nx-boot-maven postinstall:   signal: null,
.../node_modules/@jnxplus/nx-boot-maven postinstall:   output: [
.../node_modules/@jnxplus/nx-boot-maven postinstall:     null,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     Buffer(0) [Uint8Array] [],
.../node_modules/@jnxplus/nx-boot-maven postinstall:     Buffer(141) [Uint8Array] [
.../node_modules/@jnxplus/nx-boot-maven postinstall:        69, 114, 114, 111, 114,  58,  32,  73, 110, 118,  97, 108,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       105, 100,  32, 111, 114,  32,  99, 111, 114, 114, 117, 112,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       116,  32, 106,  97, 114, 102, 105, 108, 101,  32,  47,  98,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       117, 105, 108, 100, 115,  47, 106, 117, 108, 105, 117, 115,
.../node_modules/@jnxplus/nx-boot-maven postinstall:        98,  97, 101, 114,  47, 116, 101,  99, 104, 120,  47, 115,
.../node_modules/@jnxplus/nx-boot-maven postinstall:        97, 110, 100,  98, 111, 120, 101, 115,  47, 108, 105, 110,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       100,  97,  47, 116, 101, 115, 116,  45, 100, 105, 114,  45,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       111, 112, 116, 105, 111, 110,  47, 110, 111, 100, 101,  95,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       109, 111, 100, 117,
.../node_modules/@jnxplus/nx-boot-maven postinstall:       ... 41 more items
.../node_modules/@jnxplus/nx-boot-maven postinstall:     ]
.../node_modules/@jnxplus/nx-boot-maven postinstall:   ],
.../node_modules/@jnxplus/nx-boot-maven postinstall:   pid: 181,
.../node_modules/@jnxplus/nx-boot-maven postinstall:   stdout: Buffer(0) [Uint8Array] [],
.../node_modules/@jnxplus/nx-boot-maven postinstall:   stderr: Buffer(141) [Uint8Array] [
.../node_modules/@jnxplus/nx-boot-maven postinstall:      69, 114, 114, 111, 114,  58,  32,  73, 110, 118,  97, 108,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     105, 100,  32, 111, 114,  32,  99, 111, 114, 114, 117, 112,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     116,  32, 106,  97, 114, 102, 105, 108, 101,  32,  47,  98,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     117, 105, 108, 100, 115,  47, 106, 117, 108, 105, 117, 115,
.../node_modules/@jnxplus/nx-boot-maven postinstall:      98,  97, 101, 114,  47, 116, 101,  99, 104, 120,  47, 115,
.../node_modules/@jnxplus/nx-boot-maven postinstall:      97, 110, 100,  98, 111, 120, 101, 115,  47, 108, 105, 110,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     100,  97,  47, 116, 101, 115, 116,  45, 100, 105, 114,  45,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     111, 112, 116, 105, 111, 110,  47, 110, 111, 100, 101,  95,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     109, 111, 100, 117,
.../node_modules/@jnxplus/nx-boot-maven postinstall:     ... 41 more items
.../node_modules/@jnxplus/nx-boot-maven postinstall:   ]
.../node_modules/@jnxplus/nx-boot-maven postinstall: }
.../node_modules/@jnxplus/nx-boot-maven postinstall: Node.js v18.16.1
.../node_modules/@jnxplus/nx-boot-maven postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by khalilou88** [comment]
Hi @gitLinda Are you using both nx-maven and nx-boot-maven in the same repo? Like this issue https://github.com/khalilou88/jnxplus/issues/338

**Comment by gitLinda** [comment]
No, only nx-boot-maven

**Comment by khalilou88** [comment]
I will remove linters from nx-maven and nx-gradle and provide alternative using maven and gradle plugins (Maybe extract linters in a separate lib).
I recommend moving to nx-maven to have this feature, nx-maven and nx-boot-maven have the same limitation.

**Comment by khalilou88** [comment]
@gitLinda Now nx-maven (0.11.2) don't install linters anymore (same for nx-gradle).
Planning to add nx-ktlint and nx-checkstyle plugins.
