### ISSUE TITLE
Setup problem: Cannot read properties of undefined (reading 'undefined')

### ISSUE THREAD

**Issue by gausss** [khalilou88/jnxplus#517]
Hi, 

we would like to add java/maven apps to our monorepo. Installing and initializing the nx-maven plugin seems to work fine. We have an initialized maven wrapper and a root pom.xml. 

Next we want to add an application using `nx generate @jnxplus/nx-maven:application my-app`. The app is generated and a corresponding module is added to the root pom. If we want to build the root or my-app both now fail with the following message.

` Failed to process project dependencies with "@jnxplus/nx-maven". Cannot read properties of undefined (reading 'undefined')`.

If we remove the module entry from the root pom the maven build is triggered successfully but of course it cannot find the my-app application anymore.
```
nx run my-app:build

Executor ran for Build: {"task":"install","keepItRunning":false}
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: :my-app @ 
[ERROR] Could not find the selected project in the reactor: :my-app -> [Help 1]
```

Any hints on what is going wrong?

**Comment by khalilou88** [comment]
Hi @gausss I think the problem is when building the graph. Now we use the NxPluginV2. Do you have a recent version of nx?

**Comment by gausss** [comment]
Just updated from 16.8 to 16.10 which solved the problem. Thanks for the hint :)
