### ISSUE TITLE
Generating maven projects in a subfolder

### ISSUE THREAD

**Issue by khalilou88** [khalilou88/jnxplus#519]
To isolate maven root project from nx root project and have better affected experience we are planning to generate all maven project in a sub folder.  

For that we will use a `mavenRootDirectory` variable. 

during init we need to to choose this variable

we will try to put  it inside nx.json as a first option, or inside a `.env file` (in root folder)

EDIT:
https://nx.dev/recipes/tips-n-tricks/define-environment-variables

NX_maven_Root_Directory inside `.env` file

EDIT: final solution use nx-maven subefloder without use of a en var

**Comment by jbadeau** [comment]
Curious how tinesoft does it

https://github.com/tinesoft/nxrocks/pull/179

**Comment by khalilou88** [comment]
@jbadeau I don't know about nx-spring-boot plugin and what i want to do is near what nx do with `workspaceLayout`.
Maybe we can try to find the first pom.xml to find mavenRootDirectory

**Comment by jbadeau** [comment]
if you can support multiple roots like:
<img width="848" alt="Screenshot 2023-10-14 at 13 42 01" src="https://github.com/khalilou88/jnxplus/assets/152763/cd297057-2792-4d7a-9d2d-93b868ed8c62">

**Comment by khalilou88** [comment]
That will make the plugin hard to use and understand. For me we should use one maven for all projects. And we should have one root pom.xml (or inside mavenRootDirectory)  so every pom.xml can inherent from it.

**Comment by khalilou88** [comment]
another way to find mavenRootDirectory in my opinion is `nx show projects withTarget=nx-maven` and choose the project based on projectRoot

**Comment by jbadeau** [comment]
It u have a prerelease I’ll be happy to try it

**Comment by khalilou88** [comment]
@jbadeau I am working on implementing it

**Comment by jbadeau** [comment]
Cool,

Much appreciated, just trying to avoid rework for you.

**Comment by jbadeau** [comment]
Cool, just trying to avoid rework for you.

**Comment by jbadeau** [comment]
https://github.com/nrwl/nx/pull/19589

**Comment by khalilou88** [comment]
@jbadeau seems what we are looking for (if I understand well)
But I am happy with the `nx-maven` as a subfolder. Finishing the tests and will publish a new version

**Comment by jbadeau** [comment]
Ok, do u publish as prerelease or are u sure it’s fine?

**Comment by khalilou88** [comment]
prerelease don't work good for me, so i will publish a new version.
This feature is not the default option so I don't think will create a problem (tests are working fine). 
Also it's a good feature so it's will not change in the future except maybe giving the possibility to change the folder name.

**Comment by khalilou88** [comment]
I published version 0.12.0 with this feature. Please use `useSubfolder` option :  `nx generate @jnxplus/nx-maven:init --parentProjectName ${parentProjectName} --useSubfolder`

**Comment by jbadeau** [comment]
works! :)

Any change we can customize the subfolder name? I could make a pr.

**Comment by khalilou88** [comment]
For now it's not possible, but if you can find the rootproject based on a tag or variable, we can update this function:

```
export function getMavenRootDirectory() {
  const pomXmlPath = path.join(workspaceRoot, 'pom.xml');
  if (fs.existsSync(pomXmlPath)) {
    return '';
  }
  return 'nx-maven';
}
```

**Comment by khalilou88** [comment]
closing this issue. next changes will be here https://github.com/khalilou88/jnxplus/issues/535

**Comment by khalilou88** [comment]
This option is changed in version 0.13.0  to be mavenRootDirectory
