### ISSUE TITLE
 Project at . has no name provided. - Upgraded Nx to 17.1.2

### ISSUE THREAD

**Issue by nosaku** [khalilou88/jnxplus#616]
After upgrading to Nx 17.1.2 when running Angular application getting the below error:

 Project at . has no name provided.

It is failing in project-configuration-utils.js at the below. I added some debugging code (json stringify as I never get console.log to work) and this is what I get...

        if (!configuration.name) {
            throw new Error(`Project at ${root}, ${configuration} has no name provided.` + JSON.stringify(configuration));
        }

Project at ., [object Object] has no name provided.{"root":".","type":"lib","targets":{"build":{"executor":"@jnxplus/nx-maven:run-task","options":{"task":"install"}}},"tags":["nx-maven"]}

**Comment by khalilou88** [comment]
@nosaku You need to use the last version of the plugin. It's was fixed
