### ISSUE TITLE
Package Name 

### ISSUE THREAD

**Issue by gpallas16** [khalilou88/jnxplus#69]
Amazing tool and very easy to use. There is a problem in package names thought. Let's say I have a grouping folder e.g. backend inside the apps folder

root
  |__apps
        |__ backend

If I add the project in the directory backend/newprojectname, the package name of the app takes the full path and becomes more
less unusable ie com.example.backend.newprojectname, where it should be com.example.newprojectname.

So a good implementation would be to take in consideration just the last folder of the directory, so the package name generation 
would be correct, or an extra option to manually add the package name in the creation state.

Thank you again for this great plugin.

**Comment by khalilou88** [comment]
@gpallas16 Thanks for this issue. You are right the default value should be simple like https://start.spring.io/
I will made the changes
no need for an extra option to change the package, you can use the groupId for that
Summary, 

- create a project with name newprojectname ==> com.example.newprojectname as package
- create a project with name newprojectname  and groupId equal to com.example.backend ==> com.example.backend.newprojectnameas

**Comment by khalilou88** [comment]
Actually this feature was asked by @lwhiteley  here https://github.com/khalilou88/jnxplus/issues/15.
We need an extra option to handle both like isShortPackage

**Comment by gpallas16** [comment]
I think the clearest solution to prevent this issue would be to have the option to manually add the package name in the creation state. There is no need to be generated from the directory, I mean the directory could end up in a macaroni state a/b/c/d/e/, there is no need to generate the package name based on that, besides a package name could be totally different in the end.

**Comment by lwhiteley** [comment]
> So a good implementation would be to take in consideration just the last folder of the directory

probably not a good idea maybe.. if you do this then projects that can split libraries based on features or scope can now clash.

for eg. if you have

```
> libs > cars > utils
> libs > trucks > utils
```

if only the last part is considered there will be clashes.

it should maybe be optional as @khalilou88  says to do this so it keeps consistent generally with the nx approach.

for a lot of builders nx does offer the option to choose the project name

see eg below via link
https://nx.dev/packages/react/generators/library

**Comment by khalilou88** [comment]
@gpallas16 @lwhiteley I believe a third option (lets say custom) to choose a package name is a valid feature.
For now I prefer to keep it simple and give the user the choice between a long and shirt package name.
This option is available now from the version 2.4.0 for both plugins.

I will keep digging for the custom option, I have the idea but I don't know if NX  accept a conditional option when creating a app or lib

**Comment by khalilou88** [comment]
I changed this option to be just simplePackageName in the version 5.4.0. So closing this issue because no work is expected anymore.
