### ISSUE TITLE
nx generate application needs xmldoc

### ISSUE THREAD

**Issue by nosaku** [khalilou88/jnxplus#76]
nx generate application needs xmldoc. Without installing it as dev dependency it is not working.

**Comment by khalilou88** [comment]
I never faced this problem when testing but I was expecting it some day. This is why I will use peerDependencies.
this feature is not published it and I believe is will solve the problem

**Comment by nosaku** [comment]
Hi @khalilou88 thank you for acknowledging the issue. I think the peerDependencies didn't resolve it. So I installed it as a dev dependency as workaround. I guess this is ok.

**Comment by khalilou88** [comment]
@nosaku You are right. xmldoc was missing from the plugin deps. I added it in the version @jnxplus/nx-boot-maven@2.4.1.
I believe you can remove xmldoc from your deps.

**Comment by khalilou88** [comment]
I catch this issue in smoke test that I added to test the real plugin.
I moved xmldoc dep from peerDependencies to normal Dependencies to fix this issue.
