### ISSUE TITLE
Extra blank lines in generated / updated pom.xml

### ISSUE THREAD

**Issue by nosaku** [khalilou88/jnxplus#79]
When generating the pom.xml or updating (like when adding a new library with existing project as dependency), extra blank lines are added after each line. Can these blank lines be removed so I can try to preserve the formatting as close as possible?

**Comment by nosaku** [comment]
I think the xmldoc toString adds the extra new lines... if we compress toString and then again do a toString it may work... here is my try:

`var xmldoc = require('xmldoc');

var xmlString =
  `<suggestions>
  <book title="Twilight"/>
  <book title="Twister"/>
</suggestions>`;
var originalXmlText = new xmldoc.XmlDocument(xmlString);
console.log('original:', originalXmlText.toString());
var doubleCompressXmlText = new xmldoc.XmlDocument(new xmldoc.XmlDocument(xmlString).toString({ compressed: true }));
console.log('double xmldoc:', doubleCompressXmlText.toString());
`

**Comment by khalilou88** [comment]
Hi @nosaku , thanks I agree this is somthing we can improve.
Please create a Pull Request and i will merge it to remove this extras lines

**Comment by khalilou88** [comment]
I made a test and `toString({ compressed: true })` work will because `@prettier/plugin-xml` format the xml file after.
we need to add again the first line `<?xml version="1.0" encoding="UTF-8"?>` because `xmldoc` remove it.
here the issue in `xmldoc` repo : https://github.com/nfarina/xmldoc/issues/60

**Comment by nosaku** [comment]
> I made a test and `toString({ compressed: true })` work will because `@prettier/plugin-xml` format the xml file after. we need to add again the first line `<?xml version="1.0" encoding="UTF-8"?>` because `xmldoc` remove it. Also we need to remove extra blank line from the xml templates here the issue in `xmldoc` repo : [nfarina/xmldoc#60](https://github.com/nfarina/xmldoc/issues/60)

Ok great thanks... shall I create a pull request and try?

**Comment by khalilou88** [comment]
@nosaku yes please

**Comment by nosaku** [comment]
@khalilou88 I have made changes in my fork... can you please check once and let me know?
[https://github.com/nosaku/jnxplus/tree/feature/xmldoc-changes](url)

**Comment by khalilou88** [comment]
@nosaku Thanks, I run the code on local using a e2e test and the result is much better.
Please create a PR and I will merge it, then I will publish a new version

**Comment by nosaku** [comment]
@khalilou88 Thank you... created the PR.

**Comment by khalilou88** [comment]
@nosaku the version `@jnxplus/nx-boot-maven@2.4.0` contain your contribution. Thanks for your help.
If you have another request don't hesitate to open another issue

**Comment by nosaku** [comment]
Great... thank you @khalilou88
