### ISSUE TITLE
Format kotlin projects

### ISSUE THREAD

**Issue by khalilou88** [khalilou88/jnxplus#8]
We use "prettier-plugin-kotlin" to format kotlin projects but it's not working.
We need to find another solution

**Comment by iguissouma** [comment]
ktlint format works better I tested both.
Maybe add a format target that use ktlint for apps or libs using kotlin.
`./node_modules/@jnxplus/ktlint/ktlint -F "libs/my-lib/src/**/*.kt"`

I don think it's possible to develop a prettier plugin based on ktlint, so prettier invoke ktlint and get the output and overwrite the file with the result.

**Comment by khalilou88** [comment]
Now we can  use `kformat my-project` to format a kotlin project.

**Comment by vladimirdrayling** [comment]
@khalilou88 do you plan to add `nx affected:kformat`? It would be easier to format all touched libs, instead of formatting every single lib separately
