### ISSUE TITLE
npm install dependency problems

### ISSUE THREAD

**Issue by niksoft123** [khalilou88/jnxplus#94]
Hello,

I'm facing the following problem when trying to migrate my workspace to the latest nx version 14.7.6.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: codix-web@0.0.0
npm ERR! Found: @nrwl/devkit@14.7.6
npm ERR! node_modules/@nrwl/devkit
npm ERR!   dev @nrwl/devkit@"14.7.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nrwl/devkit@"~14.5.10" from @jnxplus/nx-boot-gradle@2.4.0
npm ERR! node_modules/@jnxplus/nx-boot-gradle
npm ERR!   dev @jnxplus/nx-boot-gradle@"^2.4.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```
My npm version is 8.19.1 and my node is 16.14.1.

I suppose that if I use --legacy-peer-deps it will work, but is it ok ?

If you have any suggestions or you can make a fix bumping your peer dependencies or moving them to the dependencies section it will be great.

**Comment by khalilou88** [comment]
Hi @niksoft123 just published @jnxplus/nx-boot-gradle@2.5.0 with nx@14.7.6. Hope it will solve your issue.

**Comment by khalilou88** [comment]
I will keep the issue open to change peerdeps to use (^) and be Compatible with Nx version. In the past Nx make a break change here https://github.com/khalilou88/jnxplus/issues/41. This is why I made this change but I believe it's not good

**Comment by khalilou88** [comment]
For information, I added some smoke tests to test the plugin from npm to be sure that the install process don't break in the future.
I will close this ticket
