### ISSUE TITLE
Export nx-maven run-task executor

### ISSUE THREAD

**Issue by gitLinda** [khalilou88/jnxplus#982]
Hi!

Would it be possible to export the `nx-maven:run-task` executor? I would like to call it programmatically.

Thanks :)

**Comment by khalilou88** [comment]
Hi @gitLinda,

I added the export in version 0.43.0.

Let me know if it works for you or I miss something since I didn't test it.

**Comment by gitLinda** [comment]
Works well! Thanks for the fast update
